[package]
name = "calendar_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
chrono = { version = "0.4", features = ["clock"] }
icalendar = "0.16"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
